name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Install Gomobile
      run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      id: buildRelease
      run: ./gradlew assembleGithubRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
      path: app/build/outputs/apk/github/release/*.apk

    - name: LS
      run: |
          ls -l app/build
          ls -l app/build/generated
          ls -l app/build/kotlin
          ls -l app/build/tmp
